<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ProofShift.Graph</RootNamespace>
    <AssemblyName>ProofShift.Graph</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ProofShift.Domain/ProofShift.Domain.csproj" />
    <ProjectReference Include="../ProofShift.Configuration/ProofShift.Configuration.csproj" />
  </ItemGroup>
</Project>
