<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
    <PackageVersion Include="Net.IBM.Data.Db2" Version="10.0.0.300" />
    <PackageVersion Include="Net.IBM.Data.Db2-lnx" Version="10.0.0.300" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.15.0" />
    <PackageVersion Include="Testcontainers" Version="4.15.0" />
  </ItemGroup>
</Project>
