<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ProofShift.Configuration</RootNamespace>
    <AssemblyName>ProofShift.Configuration</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ProofShift.Domain/ProofShift.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
