<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ProofShift.Configuration/ProofShift.Configuration.csproj" />
    <ProjectReference Include="../../src/ProofShift.Domain/ProofShift.Domain.csproj" />
  </ItemGroup>
</Project>
