CREATE TABLE dbo.MEMBER (
    MEMBER_ID varchar(12) NOT NULL PRIMARY KEY,
    FIRST_NM nvarchar(120) NOT NULL,
    STATUS_CD char(1) NOT NULL,
    BIRTH_DT date NOT NULL,
    ENROLL_DT date NOT NULL
);

CREATE TABLE dbo.EMPLOYMENT_HISTORY (
    EMPLOYMENT_ID varchar(16) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    EMPLOYER_CD varchar(12) NOT NULL,
    PERIOD_FROM date NOT NULL,
    PERIOD_TO date NULL,
    EMPLOYMENT_STATUS varchar(12) NOT NULL
);

CREATE TABLE dbo.CONTRIBUTION (
    TRANSACTION_ID varchar(20) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    PAY_PERIOD char(7) NOT NULL,
    CONTRIBUTION_CATEGORY varchar(16) NOT NULL,
    CONTRIBUTION_AMT decimal(19, 4) NOT NULL
);

CREATE TABLE dbo.SERVICE_CREDIT (
    SERVICE_ID varchar(18) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    SERVICE_FROM date NOT NULL,
    SERVICE_TO date NOT NULL,
    CREDIT_AMT decimal(12, 6) NOT NULL,
    CREDIT_TYPE varchar(16) NOT NULL
);

CREATE TABLE dbo.BENEFICIARY (
    BENEFICIARY_ID varchar(16) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    RELATIONSHIP_CD varchar(16) NOT NULL,
    ALLOCATION_PCT decimal(7, 4) NOT NULL
);

CREATE TABLE dbo.RETIREMENT_ELECTION (
    ELECTION_ID varchar(16) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    OPTION_CD varchar(12) NOT NULL,
    EFFECTIVE_DT date NOT NULL
);

CREATE TABLE dbo.BENEFIT_PAYMENT (
    PAYMENT_ID varchar(20) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    PAYMENT_PERIOD char(7) NOT NULL,
    PAYMENT_DT date NOT NULL,
    GROSS_AMT decimal(19, 4) NOT NULL
);

CREATE TABLE dbo.DOCUMENT_INDEX (
    DOCUMENT_ID varchar(20) NOT NULL PRIMARY KEY,
    MEMBER_ID varchar(12) NOT NULL,
    DOCUMENT_CATEGORY varchar(20) NOT NULL,
    RELATIVE_PATH nvarchar(512) NOT NULL,
    CONTENT_SHA256 char(64) NOT NULL
);
