<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ProofShift.Connectors.Sftp</RootNamespace>
    <AssemblyName>ProofShift.Connectors.Sftp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SSH.NET" />
    <ProjectReference Include="../ProofShift.Connectors.Abstractions/ProofShift.Connectors.Abstractions.csproj" />
    <ProjectReference Include="../ProofShift.Connectors.RemoteObjects/ProofShift.Connectors.RemoteObjects.csproj" />
  </ItemGroup>
</Project>
