<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ProofShift.Cli</RootNamespace>
    <AssemblyName>ProofShift.Cli</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ProofShift.Domain/ProofShift.Domain.csproj" />
    <ProjectReference Include="../ProofShift.Configuration/ProofShift.Configuration.csproj" />
    <ProjectReference Include="../ProofShift.Graph/ProofShift.Graph.csproj" />
    <ProjectReference Include="../ProofShift.Engine/ProofShift.Engine.csproj" />
    <ProjectReference Include="../ProofShift.Projection/ProofShift.Projection.csproj" />
    <ProjectReference Include="../ProofShift.Reporting/ProofShift.Reporting.csproj" />
    <ProjectReference Include="../ProofShift.Connectors.Abstractions/ProofShift.Connectors.Abstractions.csproj" />
    <ProjectReference Include="../ProofShift.Connectors.Postgres/ProofShift.Connectors.Postgres.csproj" />
    <ProjectReference Include="../ProofShift.Connectors.SqlServer/ProofShift.Connectors.SqlServer.csproj" />
    <ProjectReference Include="../ProofShift.Connectors.Files/ProofShift.Connectors.Files.csproj" />
    <ProjectReference Include="../ProofShift.Connectors.Csv/ProofShift.Connectors.Csv.csproj" />
  </ItemGroup>
</Project>
